#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logged:
    path: /
    controller: App\Controller\LoggedController::show
    
change_password:
    path: /chpass
    controller: App\Controller\ChangePasswordController::show
    
showLoggedOut:
    path: /lout
    controller: App\Controller\SecurityController::showLoggedOut

manageUsers:
    path: /manage
    controller: App\Controller\ManageController::show    